###############################################################################
# FILE: Makefile.config
#
# Configure the UAPI build.  Works in conjunction with Makefile.defs and
# system-wide makefiles
###############################################################################

UAPI_HOST_OS	   = UNIX
UAPI_OS            = UNIX
UAPI_TARGET_OS     = UNIX

UAPI_HOST_CPU      = I86

ifeq ($(TARGET_ARCH),arm)
  UAPI_CPU         = ARM
  UAPI_TARGET_CPU  = ARM
else
ifeq ($(TARGET_ARCH),x86)
  UAPI_CPU         = I86
  UAPI_TARGET_CPU  = I86
else
  $(error Unsupported TARGET_ARCH for ASR)
endif
endif

UAPI_COMPILER      = GNU

ifeq ($(TARGET_BUILD_TYPE),debug)
  UAPI_BUILD       = DEBUG
else
ifeq ($(TARGET_BUILD_TYPE),release)
  UAPI_BUILD       = SHIP
else
  $(error Unsupported TARGET_BUILD_TYPE for ASR)
endif
endif
