/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_NBestRecognitionResultImpl */

#ifndef _Included_android_speech_recognition_impl_NBestRecognitionResultImpl
#define _Included_android_speech_recognition_impl_NBestRecognitionResultImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_NBestRecognitionResultImpl
 * Method:    createVoicetagItemProxy
 * Signature: (JLjava/lang/String;Landroid/speech/recognition/VoicetagItemListener;)J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_NBestRecognitionResultImpl_createVoicetagItemProxy
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     android_speech_recognition_impl_NBestRecognitionResultImpl
 * Method:    getEntryProxy
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_NBestRecognitionResultImpl_getEntryProxy
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_speech_recognition_impl_NBestRecognitionResultImpl
 * Method:    getSizeProxy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_speech_recognition_impl_NBestRecognitionResultImpl_getSizeProxy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
