/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_MediaFileReaderImpl */

#ifndef _Included_android_speech_recognition_impl_MediaFileReaderImpl
#define _Included_android_speech_recognition_impl_MediaFileReaderImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_MediaFileReaderImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_MediaFileReaderImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_MediaFileReaderImpl
 * Method:    createMediaFileReaderProxy
 * Signature: (Ljava/lang/String;Landroid/speech/recognition/AudioSourceListener;)J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_MediaFileReaderImpl_createMediaFileReaderProxy
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     android_speech_recognition_impl_MediaFileReaderImpl
 * Method:    setModeProxy
 * Signature: (JLandroid/speech/recognition/MediaFileReader/Mode;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_MediaFileReaderImpl_setModeProxy
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_speech_recognition_impl_MediaFileReaderImpl
 * Method:    createAudioProxy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_MediaFileReaderImpl_createAudioProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_MediaFileReaderImpl
 * Method:    startProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_MediaFileReaderImpl_startProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_MediaFileReaderImpl
 * Method:    stopProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_MediaFileReaderImpl_stopProxy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
