/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_System */

#ifndef _Included_android_speech_recognition_impl_System
#define _Included_android_speech_recognition_impl_System
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_System
 * Method:    getAPIVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_speech_recognition_impl_System_getAPIVersion
  (JNIEnv *, jclass);

/*
 * Class:     android_speech_recognition_impl_System
 * Method:    initNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_System_initNativeObject
  (JNIEnv *, jclass);

/*
 * Class:     android_speech_recognition_impl_System
 * Method:    disposeProxy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_System_disposeProxy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
