/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_GrammarImpl */

#ifndef _Included_android_speech_recognition_impl_GrammarImpl
#define _Included_android_speech_recognition_impl_GrammarImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_GrammarImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_GrammarImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_GrammarImpl
 * Method:    loadProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_GrammarImpl_loadProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_GrammarImpl
 * Method:    unloadProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_GrammarImpl_unloadProxy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
