/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_SrecGrammarImpl */

#ifndef _Included_android_speech_recognition_impl_SrecGrammarImpl
#define _Included_android_speech_recognition_impl_SrecGrammarImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_SrecGrammarImpl
 * Method:    addItemProxy
 * Signature: (JLjava/lang/String;JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_SrecGrammarImpl_addItemProxy
  (JNIEnv *, jobject, jlong, jstring, jlong, jint, jstring);

/*
 * Class:     android_speech_recognition_impl_SrecGrammarImpl
 * Method:    addItemListProxy
 * Signature: (JLjava/lang/String;[J[I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_SrecGrammarImpl_addItemListProxy
  (JNIEnv *, jobject, jlong, jstring, jlongArray, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
