/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_DeviceSpeakerImpl */

#ifndef _Included_android_speech_recognition_impl_DeviceSpeakerImpl
#define _Included_android_speech_recognition_impl_DeviceSpeakerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_DeviceSpeakerImpl
 * Method:    initNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_DeviceSpeakerImpl_initNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     android_speech_recognition_impl_DeviceSpeakerImpl
 * Method:    startProxy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_DeviceSpeakerImpl_startProxy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     android_speech_recognition_impl_DeviceSpeakerImpl
 * Method:    stopProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_DeviceSpeakerImpl_stopProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_DeviceSpeakerImpl
 * Method:    setCodecProxy
 * Signature: (JLandroid/speech/recognition/Codec;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_DeviceSpeakerImpl_setCodecProxy
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_speech_recognition_impl_DeviceSpeakerImpl
 * Method:    setListenerProxy
 * Signature: (JLandroid/speech/recognition/DeviceSpeakerListener;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_DeviceSpeakerImpl_setListenerProxy
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_speech_recognition_impl_DeviceSpeakerImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_DeviceSpeakerImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
