/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_EmbeddedGrammarImpl */

#ifndef _Included_android_speech_recognition_impl_EmbeddedGrammarImpl
#define _Included_android_speech_recognition_impl_EmbeddedGrammarImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_EmbeddedGrammarImpl
 * Method:    compileAllSlotsProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedGrammarImpl_compileAllSlotsProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_EmbeddedGrammarImpl
 * Method:    resetAllSlotsProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedGrammarImpl_resetAllSlotsProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_EmbeddedGrammarImpl
 * Method:    saveProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedGrammarImpl_saveProxy
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
