/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_EmbeddedRecognizerImpl */

#ifndef _Included_android_speech_recognition_impl_EmbeddedRecognizerImpl
#define _Included_android_speech_recognition_impl_EmbeddedRecognizerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    getInstanceProxy
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_getInstanceProxy
  (JNIEnv *, jobject);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    configureProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_configureProxy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    setListenerProxy
 * Signature: (JLandroid/speech/recognition/RecognizerListener;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_setListenerProxy
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    recognizeProxy
 * Signature: (JJ[J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_recognizeProxy
  (JNIEnv *, jobject, jlong, jlong, jlongArray);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    createEmbeddedGrammarProxy
 * Signature: (JLjava/lang/String;Landroid/speech/recognition/GrammarListener;)J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_createEmbeddedGrammarProxy
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    stopProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_stopProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    setParametersProxy
 * Signature: (JLjava/util/Hashtable;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_setParametersProxy
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    getParametersProxy
 * Signature: (JLjava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_getParametersProxy
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_speech_recognition_impl_EmbeddedRecognizerImpl
 * Method:    resetAcousticStateProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EmbeddedRecognizerImpl_resetAcousticStateProxy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
