/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_EntryImpl */

#ifndef _Included_android_speech_recognition_impl_EntryImpl
#define _Included_android_speech_recognition_impl_EntryImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_EntryImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_EntryImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_EntryImpl
 * Method:    getLiteralMeaningProxy
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_speech_recognition_impl_EntryImpl_getLiteralMeaningProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_EntryImpl
 * Method:    getSemanticMeaningProxy
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_speech_recognition_impl_EntryImpl_getSemanticMeaningProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_EntryImpl
 * Method:    getConfidenceScoreProxy
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_android_speech_recognition_impl_EntryImpl_getConfidenceScoreProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_EntryImpl
 * Method:    getProxy
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_speech_recognition_impl_EntryImpl_getProxy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_speech_recognition_impl_EntryImpl
 * Method:    keysProxy
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_android_speech_recognition_impl_EntryImpl_keysProxy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
