/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_LoggerImpl */

#ifndef _Included_android_speech_recognition_impl_LoggerImpl
#define _Included_android_speech_recognition_impl_LoggerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_LoggerImpl
 * Method:    initNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_LoggerImpl_initNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     android_speech_recognition_impl_LoggerImpl
 * Method:    setLoggingLevelProxy
 * Signature: (JLandroid/speech/recognition/Logger/LogLevel;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_LoggerImpl_setLoggingLevelProxy
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_speech_recognition_impl_LoggerImpl
 * Method:    setPathProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_LoggerImpl_setPathProxy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_speech_recognition_impl_LoggerImpl
 * Method:    errorProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_LoggerImpl_errorProxy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_speech_recognition_impl_LoggerImpl
 * Method:    warnProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_LoggerImpl_warnProxy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_speech_recognition_impl_LoggerImpl
 * Method:    infoProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_LoggerImpl_infoProxy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_speech_recognition_impl_LoggerImpl
 * Method:    traceProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_LoggerImpl_traceProxy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_speech_recognition_impl_LoggerImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_LoggerImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
