/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_VoicetagItemImpl */

#ifndef _Included_android_speech_recognition_impl_VoicetagItemImpl
#define _Included_android_speech_recognition_impl_VoicetagItemImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_VoicetagItemImpl
 * Method:    createVoicetagProxy
 * Signature: (Ljava/lang/String;Landroid/speech/recognition/VoicetagItemListener;)J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_VoicetagItemImpl_createVoicetagProxy
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     android_speech_recognition_impl_VoicetagItemImpl
 * Method:    getAudioProxy
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_speech_recognition_impl_VoicetagItemImpl_getAudioProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_VoicetagItemImpl
 * Method:    setAudioProxy
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_VoicetagItemImpl_setAudioProxy
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     android_speech_recognition_impl_VoicetagItemImpl
 * Method:    saveVoicetagProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_VoicetagItemImpl_saveVoicetagProxy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_speech_recognition_impl_VoicetagItemImpl
 * Method:    loadVoicetagProxy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_VoicetagItemImpl_loadVoicetagProxy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_VoicetagItemImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_VoicetagItemImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
