/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_AudioStreamImpl */

#ifndef _Included_android_speech_recognition_impl_AudioStreamImpl
#define _Included_android_speech_recognition_impl_AudioStreamImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_AudioStreamImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_AudioStreamImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
