/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_WordItemImpl */

#ifndef _Included_android_speech_recognition_impl_WordItemImpl
#define _Included_android_speech_recognition_impl_WordItemImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_WordItemImpl
 * Method:    initNativeObject
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_WordItemImpl_initNativeObject
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     android_speech_recognition_impl_WordItemImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_WordItemImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
