/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_speech_recognition_impl_MediaFileWriterImpl */

#ifndef _Included_android_speech_recognition_impl_MediaFileWriterImpl
#define _Included_android_speech_recognition_impl_MediaFileWriterImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_speech_recognition_impl_MediaFileWriterImpl
 * Method:    createMediaFileWriterProxy
 * Signature: (Landroid/speech/recognition/MediaFileWriterListener;)J
 */
JNIEXPORT jlong JNICALL Java_android_speech_recognition_impl_MediaFileWriterImpl_createMediaFileWriterProxy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_speech_recognition_impl_MediaFileWriterImpl
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_MediaFileWriterImpl_deleteNativeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_speech_recognition_impl_MediaFileWriterImpl
 * Method:    saveProxy
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_speech_recognition_impl_MediaFileWriterImpl_saveProxy
  (JNIEnv *, jobject, jlong, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
